name: fcheck
description: A CLI tool for analyzing Flutter and Dart code quality, checking project metrics, comment ratios, class organization, hardcoded strings, and source sorting validation.
version: 0.8.0
repository: https://github.com/vteam-com/fCheck.git
topics:
  - analysis
  - architecture
  - code-style
  - lint
  - validation

executables:
  fcheck:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^10.0.2
  args: ^2.7.0
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.29.0
  lints: ^6.1.0
