name: fcheck
description: A tool for checking quality of Flutter apps.
version: 0.1.0
repository: https://github.com/vteam-com/fCheck.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
