name: fcheck
description: A tool for checking quality of Flutter apps.
version: 0.1.0
repository: https://github.com/vteam-com/fCheck.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^10.0.1
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.29.0
  lints: ^6.0.0
